# Generated by Django 4.1.1 on 2022-10-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.IntegerField()),
                ("summary", models.TextField(max_length=2000)),
                ("education", models.TextField(max_length=2000)),
                ("experience", models.TextField(max_length=1000)),
                ("project", models.TextField(max_length=1000)),
                ("certificate", models.TextField(max_length=1000)),
                ("career_objective", models.TextField(max_length=1000)),
            ],
        ),
    ]
